name: Initialize

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove this action
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm ./.github/workflows/init.yml
          git commit -m 'Remove init.yml'
          git push
